<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite11f93e25108930ae85cbb0eddf9c2a6
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/App',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite11f93e25108930ae85cbb0eddf9c2a6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite11f93e25108930ae85cbb0eddf9c2a6::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite11f93e25108930ae85cbb0eddf9c2a6::$classMap;

        }, null, ClassLoader::class);
    }
}
